version: "3.3"
services:
  speechrec:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    restart: always
    runtime: nvidia
    volumes:
      - ../app:/app
    environment:
      - HOST=0.0.0.0
      - PORT=5001
    ports:
      - 5001:5001
    command: "python3.10 run.py"
